# Generated by Django 4.2.2 on 2023-06-13 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(default='国際情報学部', max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('credit_number', models.IntegerField(default=2)),
                ('required_or_select', models.IntegerField(choices=[(0, 'Required'), (1, 'Select')])),
                ('minimum_grade_level', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('前期', '前期'), ('後期', '後期'), ('夏季集中', '夏季集中'), ('通年', '通年')], default='前期', max_length=20)),
                ('day_of_week', models.CharField(choices=[('なし', 'NULL'), ('月', 'Monday'), ('火', 'Tuesday'), ('水', 'Wednesday'), ('木', 'Thursday'), ('金', 'Friday'), ('土', 'Saturday')], max_length=5)),
                ('period', models.IntegerField()),
                ('classroom', models.CharField(blank=True, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='credit_calculator.course')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('credit_minimum', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('semester', models.IntegerField()),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.courseschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.courseschedule')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CourseProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professors', to='credit_calculator.courseschedule')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.professor')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_calculator.genre'),
        ),
    ]
