# Generated by Django 4.2.2 on 2023-06-20 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseschedule',
            name='day_of_week',
            field=models.CharField(choices=[('なし', 'その他'), ('月', '月曜'), ('火', '火曜'), ('水', '水曜'), ('木', '木曜'), ('金', '金曜'), ('土', '土曜')], max_length=5),
        ),
    ]
