# Generated by Django 4.2.2 on 2023-07-02 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_calculator', '0002_alter_courseschedule_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='credit_calculator.genre'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='grade',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='semester',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
